name: Package App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Package for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn dist
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: ${{ !startsWith(github.ref, 'refs/tags/') }}
          files: out/PushPin*.{dmg,exe,AppImage}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
